// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	ID string `path:"id"`
}

type ExpandResp struct {
	LongUrl string `json:"longUrl"`
}

type ShortenReq struct {
	LongUrl      string `json:"longUrl"`
	ExpiresAfter int64  `json:"expiresAfter,optional"`
}

type ShortenResp struct {
	ID string `json:"id"`
}
