version: '3'

services:
  scylla:
    image: scylladb/scylla
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
      - 10000:10000
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - .docker/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
